### ISSUE TITLE
Add GH workflow and actions template

### ISSUE THREAD

**Issue by himanshuagarwal456** [biosensics/.github#1]
**Is your feature request related to a problem? Please describe.**

All repos in Biosensics need to conform to general build pipeline. 
 
**Describe the solution you'd like**

Add a generic template for actions and workflow which has minimum required steps. This will be added and edited by developers working on individual repos.

**Describe alternatives you've considered**

 N/A

**Additional context**

**Comment by obermillerk** [comment]
The generalized workflows have been added with comments indicating where changes may be needed, but the actions are all specific to the projects, so no templates were added. I think this should be sufficient, as long as the documentation of the release process is read as well. I'm hesitant to include it here since this repo is public to support the issue templates, and I'm not sure how much we want to put in here that isn't absolutely necessary.
